- hosts: _lemp
  become: true
  vars:
    mysql_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38623831323035623231303464306139623039376434353461636438393634623361353361376364
          6534666263303764336565303263653131343933313337350a623030666266666237383233306162
          32353037356162346437363235306638353334613463323763626433663537636434303531343734
          6131356463353132640a363634633235313366303533633837333138656466383137306665313436
          6436
  tasks:

    - name: Install prerequisites for Docker
      apt: name={{ item }} state=latest update-cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'python3-pip']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt: name={{ item }} state=latest update-cache=yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Install Docker SDK
      pip:
        name: docker

    - name: Create mysql container
      docker_container:
        name: mysql_task6
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        state: started
        published_ports:
          - 3306:3306
        env:
            MYSQL_ROOT_PASSWORD: "{{ mysql_pass }}"
    
    - name: Copy dump file to hosts
      copy:
        src: /home/ubuntu/dump1.sql
        dest: /home/ubuntu/dump1.sql        
        
    - name: Copy ssh key to Docker container
      command: docker cp /home/ubuntu/dump1.sql mysql_task6:/home/jenkins
	
    - name: Restore database from dump
      command: docker exec -i mysql_task6 sh -c 'exec mysql -u root -p "{{ mysql_pass }}"' < /home/ubuntu/dump1.sql
      